### ISSUE TITLE
Automatic configuration loading

### ISSUE THREAD

**Issue by djhurio** [nbbrd/beanzooka#29]
Would be nice to have an automatic configuration loading from the same folder where the `exe` or `jar` is located. For example, if the folder contains file with a name `config.xml`, it is loaded automatically when Beanzooka is launched.

**Comment by charphi** [comment]
Thanks for your suggestion.

I'm not sure how to implement this in a satisfying way:
- which name should be the default one? (default.xml, config.xml, beanzooka.xml, ...)
- which folder should be the default one? (user folder, document folder, execution folder, application folder, ...)

Beanzooka already remembers the last opened folder so you don't have to search all the folder hierarchy each time you want to open a config.
There are also some keyboard shortcuts to fasten use. (F2 to open)

A possible solution would be to allow Beanzooka to be launched with some parameters. For example, you would have to create a desktop shortcut with a target `C:\some_path\beanzooka.exe config.xml`.
What do you think about it?

**Comment by charphi** [comment]
Done in 08049e03d6df3d656f4007622f2ba7a707f09f18 by using an optional parameter in a shortcut or in terminal.
